# Generated by Django 4.1.7 on 2023-04-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0003_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('attachment', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
