# Generated by Django 4.1.7 on 2023-04-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0005_sendemailmessage_message_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendEmailMessage',
        ),
    ]
