# Generated by Django 4.1.7 on 2023-04-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0008_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
