# Generated by Django 4.1.7 on 2023-04-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0010_userfollowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_follower',
            new_name='following_user_id',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_following',
            new_name='user_id',
        ),
    ]
