# Generated by Django 4.1.7 on 2023-04-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0013_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
