# Generated by Django 4.1.7 on 2023-04-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0016_alter_followers_who_follows_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='who_is_following',
            new_name='another_user',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='who_follows_user',
            new_name='user',
        ),
    ]
