# Generated by Django 4.1.7 on 2023-05-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='cotent',
            new_name='content',
        ),
    ]
