# Generated by Django 4.1.7 on 2023-03-24 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('role', models.CharField(choices=[('DEV', 'developer'), ('STU', 'dtudent'), ('INT', 'internship'), ('MAN', 'project manager'), ('EMP', 'employer'), ('ADM', 'admin'), ('TEC', 'teacher'), ('OTH', 'other')], default='ADM', max_length=3)),
                ('avatar', models.ImageField(default='default_user_img.jpg', upload_to='images/')),
                ('stop_notifications', models.BooleanField(default=False, help_text='if user wants to turn off email notification when question has been answered')),
            ],
        ),
    ]
